name: 'Generate document'
on:
  push:
    branches: [ main ]
    tags:
      - '*'
defaults:
  run:
    working-directory: .
jobs:
  build_deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tex to PDF
        uses: ./actions/xelatex
        env:
          OUT_DIR: public

      - name: Download artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: public/