name: 'Release resume'
on:
  release:
    types: [published]
defaults:
  run:
    working-directory: .
jobs:
  release:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tex to PDF
        uses: ./actions/xelatex
        env:
          OUT_DIR: public

      - name: Download artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.GITHUB_REF_NAME }}
          path: public/